### ISSUE TITLE
Easier way to play individual parts?

### ISSUE THREAD

**Issue by timrog** [xrrhythmsuk/xruk-player#26]
@BirchBirchBirch - I see you've added separate patterns for separate parts. 

<img width="758" alt="image" src="https://user-images.githubusercontent.com/809621/228045032-ad62a040-1c79-4224-89ba-b5329bb30e91.png">

We can already play individual parts but it's not necessarily that easy. If I added an easier way to play individual parts, would that solve the problem?

**Comment by BirchBirchBirch** [comment]
Hi Tim,

Yes, if we could show each individual part how I've got it here, looped with a shaker keeping time underneath, downloadable, and indented or something to differentiate it from the breaks, that would be great. (The tweaks to get the whistle in to work is about as far as I trust myself when it comes to fiddling with the code...) As you say, soloing individual parts is already possible but not the most user friendly.

I can make a Shaker Time and a Shaker Time (Stolen) general break if that would help.

**Comment by timrog** [comment]
@BirchBirchBirch This was a rough idea how I thought we could improve it. Look through the shonky design, we can improve on that. 

The main page for each tune becomes a player with a prominent play button and solo buttons for the parts. Those would control soloing for the whole page. 

Below, you can play the song, or you can click to expand each break. Expanding the break brings up the grid that currently appears in a separate tab. We can highlight the currently soloed part to make it more prominent as shown. We could also automatically add a click track if a part is soloed.

I think this would give a more palatable, immersive experience than how it works currently. Does it make sense and what do you think?

![image](https://user-images.githubusercontent.com/809621/229186585-77609e02-095c-4dab-b2e7-5336557d8ec1.png)

**Comment by BirchBirchBirch** [comment]
That all sounds great to me! As I was saying elsewhere, I think making the notation optional is a good move.

We could also perhaps make the mnemonics visible and spaced out for the right time (I don't know if adapting the player cursor would work there?) and have an edit button so people could do their own.

This ties into the idea of having PDFs at all, but if you were happy implementing the break symbols I was thinking the only real issue with displaying them is A (everybody answers), which you could perhaps define as part of the break as needed along with ad hoc symbols such as snR (snare + repi).
