### ISSUE TITLE
Filtering tunes and breaks by difficulty/commonness

### ISSUE THREAD

**Issue by BirchBirchBirch** [xrrhythmsuk/xruk-player#27]
To support newer bands and players, it would be good to have a dropdown in the navigation panel to display "core", "common", "new" and "all" tunes and breaks.

Tunes have category labels already, although this hasn't been carried over to the main XR Player navigation side panel from the RoR Player (though it is still there in the Compose view).

Individual breaks don't have this feature, however, so I propose adding a "category:" field for each break in a tune (and the General Breaks) and displaying or hiding them accordingly.

**Comment by timrog** [comment]
Yes this was a feature of the old player, but I removed it because it seemed overkill for just a handful of tunes. I can add it back in easily. 

I also combined all the breaks into "General breaks" because most of RoR's special breaks were irrelevant. But maybe now is the time to break it apart into separate sections.

**Comment by BirchBirchBirch** [comment]
That would be great. (Plus extending it to breaks as well.)

I totally see what you mean, but for a new band even though it's not as many songs as RoR it's still a huge amount to learn, and some of it is more common and accessible than other bits. Also I don't think any one RoR band plays all of the tunes.

Also agree with combining the General Breaks. There's certainly a lot of them that I don't think we'd be interested in including – it's a shame we didn't discuss it to avoid you having to rename all those sound clips for the chants! I think keeping them on one page is good, but it might be good to have sections on the page like how I've broken it up in the notation page, which would then also let us have text descriptions of the breaks that wouldn't work with sound files.

**Comment by BirchBirchBirch** [comment]
Bump on this as having levels of tunes and breaks sounds like a feature that would help for playing and whistling at national things from discussions on the skillsharing chat
