### ISSUE TITLE
Splash page

### ISSUE THREAD

**Issue by BirchBirchBirch** [xrrhythmsuk/xruk-player#29]
Instead of the current alternation between opening Bhangra and Sambasso on launch, I propose we have a cover page (differing for "core"/"common"/"new"/"all") to explain what the purpose of the player is and provide download links to the relevant whole tune set PDFs.

**Comment by timrog** [comment]
@BirchBirchBirch _About_ page added - edit it [here](https://github.com/xrrhythmsuk/xruk-player/blob/master/assets/about.md). 

I've got an idea to jazz it up with some stylized links for each tune which I'll work on soon.
