### ISSUE TITLE
Making tune list visible on splash page

### ISSUE THREAD

**Issue by BirchBirchBirch** [xrrhythmsuk/xruk-player#36]
While having the splash page is great, I've had feedback that now having to go over to "Listen" to get to the tunes list isn't ideal. (On mobile there's the usual three lines button, but it doesn't do anything.)

Could we have that page show the same tunes list as in the "Listen" tab?

(It might be helpful to replace the three lines button on mobile with "Tunes" in a box or something as well, as our less tech-savvy audience might not immediately know what it's for.)

I've had very positive feedback about everything else, though!

**Comment by BirchBirchBirch** [comment]
Oh sorry, I hadn't seen the very pretty tunes list! Possibly a sign it's easy to miss, though, unfortunately

**Comment by timrog** [comment]
I'd suggest you're probably an atypical user. I'd made those changes after watching some noobs navigate the site on their phones. I'll try and do the same again with these changes.

The other improvement I made was to pop up the sidebar automatically when they go to Listen (assuming it was hidden). That demonstrates its existence. So they should have two easy paths to find the tunes now.

Apart from that, I don't know what to suggest? Bigger? _More_ colourful? Move them up to the top? But then that means the intro text is lost which was the whole point of the splash screen.

The menu icon shouldn't be visible on the splash page. I'll try and remove that.

**Comment by BirchBirchBirch** [comment]
I'd agree I'm an atypical user, that was feedback I got. I can ask the person to have a go again, but I might add a note to scroll down for tunes to the blurb just to cover the bases.

The other improvements are all great!

**Comment by BirchBirchBirch** [comment]
Just had a look again and the menu icon still seems to be there on the splash page on mobile
