### ISSUE TITLE
List built-in tunes by category instead of A-Z

### ISSUE THREAD

**Issue by BirchBirchBirch** [xrrhythmsuk/xruk-player#59]
In the group call we just did on what to do at camp/put on the player, there was discussion that it would be helpful for the built-in tunes list on the left to display tunes by how common they are rather than alphabetically.

Could we have the tunes displayed with headings as below? That would probably get rid of the need to have the filter there too.

General Breaks

**Core**
Funk
Karla
Hedgehog
Samba Reggae
Bhangra

**Common**
Afoxé
Angela Davis
Sambasso
Stolen
Custard

**New and Proposed**
Drum & Bass
Jericho

P.S. The changes you've raised sound great, by the way!

**Comment by timrog** [comment]
Sure. Let me add to that list **Your tunes** a user's own compositions. And in future, a **User submitted** section for when we can allow submissions.
