### ISSUE TITLE
Change so importing a tune opens on that tune

### ISSUE THREAD

**Issue by BirchBirchBirch** [xrrhythmsuk/xruk-player#63]
I've just encountered a bit of confusion that a link for adding a tune (with attached compose song) opens to the player splash page instead of the song itself.

Could we change it so that e.g. clicking the horrendous link (which I'll be very glad to see the back of and use a file for instead!) loads and opens to that tune in Listen view? (Or Compose view if there's a compose song included.)

**Comment by timrog** [comment]
Newly generated links should be fine - hopefully you can confirm. It’s just previously generated ones where it tries to redirect you from http to https. But I’ll try and fix that.
