### ISSUE TITLE
Relabel new sharing tools for clarity?

### ISSUE THREAD

**Issue by BirchBirchBirch** [xrrhythmsuk/xruk-player#74]
I've got feedback that people used to the previous system are confused that the "Share" option has moved.

After discussing it with them, we had the thought of getting rid of the "Export .wav"/".mp3" options and having the "Share" option include a tab for exporting the current song as a .wav or .mp3 in the popup. (Perhaps the tab could be "Export sound file" and then a radio button for .wav/.mp3 and a button to generate and download the file.)

On comparing with the RoR player, though, perhaps just moving the option back to its original position might be enough.

**Comment by timrog** [comment]
Hi Birch

I'm a bit confused. What's moved from where to where? Are you talking about the Share button at the top of custom pattern editor? There's a bunch of buttons missing from there so I'll fix that soon.

![image](https://github.com/xrrhythmsuk/xruk-player/assets/809621/229273ac-3b79-42ea-a893-c5638a8a6700)

Export wav/mp3 are difficult to fit into the Share dialog works on a selection - you can't share a whole song as an Mp3 for example.

**Comment by BirchBirchBirch** [comment]
So this is on Compose, the dropdown menu that appears when you select Tools

Good to know those buttons are coming back though 😁

**Comment by timrog** [comment]
> So this is on Compose, the dropdown menu that appears when you select Tools
> 
> Good to know those buttons are coming back though 😁

Well it's just moved 3 positions up in the menu compared to RoR. There aren't seriously people saying that's confusing?
![image](https://github.com/xrrhythmsuk/xruk-player/assets/809621/b75d8fa1-5bfe-406a-afdc-6eb9eadfe2f0)
![image](https://github.com/xrrhythmsuk/xruk-player/assets/809621/4611ca7f-758c-4901-a589-ba970b48edc1)

**Comment by BirchBirchBirch** [comment]
It's true it's a small change, but that was the feedback I got. Perhaps wait to see if anyone else finds it a problem.

**Comment by timrog** [comment]
Reinstated Share button. Closing for now.

**Comment by timrog** [comment]
Reinstated Share button. Closing for now.
