### ISSUE TITLE
Add loop button to instrument solo buttons?

### ISSUE THREAD

**Issue by BirchBirchBirch** [xrrhythmsuk/xruk-player#93]
I was talking to a user who, it emerged, hadn't been able to find the loop tick box when using the player.

It probably ties into issue #87 ("loop: true" not respected in Notes view) but the user agreed that it would help to have an icon to toggle enforced looping together with the instrument solo buttons (which I continue to hear are very helpful and a big UI/UX improvement!).

**Comment by timrog** [comment]
Do you think we should just make it loop by default? I'm not really sure why anyone wouldn't want it to loop. Press play to start, press stop when you've had enough.

**Comment by BirchBirchBirch** [comment]
Hmm, I feel like having the breaks that don't loop just go through once can help people remember which ones loop and which ones don't by default?

Unless the notes view for the looping stuff has some kind of visual cue that it loops or something, I don't know
